name: Build KratosPP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install ATL
        shell: pwsh
        run: |
          choco install visualstudio2022-workload-nativedesktop --package-parameters "--add Microsoft.VisualStudio.Component.VC.ATL" --no-progress -y

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: msbuild Kratos.sln /p:Configuration=Release /p:Platform=x86 "/p:IgnoreSpecificDefaultLibraries=atls.lib"

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kratos
          path: Release/Kratos.dll
